server:
  port: 8089
spring:
  datasource:
    url: jdbc:mysql://192.168.1.3:3306/crayon?useSSL=false
    username: root
    password: yaojikai
    driver-class-name: com.mysql.jdbc.Driver
logging:
  level:
    com.jikaigg: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.jikaigg.hotel.pojo