server:
  port: 8085
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes: #网关路由配置
        - id: userservice #路由id，自定义，只要唯一即可
#          uri: http://192.168.56.104:8848/userservice #路由的目标地址http就是固定地址
          uri: lb://userservice #路由的目标地址是lb就是负载均衡，后面跟服务名称
          predicates: #路由断言，也就是判断请求是否符合路由规则的条件
            - Path=/user/** #这个是按照路径匹配，只要是/user/开头就符合要求
    nacos:
      server-addr: 192.168.56.104:8848 #nacos服务地址
      #      discovery:
      #        cluster-name: HZ   # 集群名称，SH代指上海
      config:
        file-extension: yaml