server:
  port: 8080
spring:
  application:
    name: transaction
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: yaojikai
    username: root
    url: jdbc:mysql://192.168.1.3:3306/crayon

