server:
  port: 8085
spring:
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: 192.168.56.104:8848 #nacos服务地址
      #      discovery:
      #        cluster-name: HZ   # 集群名称，SH代指上海
      config:
        file-extension: yaml
    gateway:
      routes: #网关路由配置
        - id: userservice #路由id，自定义，只要唯一即可
          #          uri: http://192.168.56.104:8848/userservice #路由的目标地址http就是固定地址
          uri: lb://userservice #路由的目标地址是lb就是负载均衡，后面跟服务名称
          predicates: #路由断言，也就是判断请求是否符合路由规则的条件
            - Path=/user/** #这个是按照路径匹配，只要是/user/开头就符合要求
#          filters:
#            - AddRequestHeader=yao,jikai
        - id: orderservice
          uri: lb://orderservice
          predicates:
            - Path=/order/**
#            - After=2031-04-13T11:11:11.010+08:00[Asia/Shanghai]  #这个时间点之后允许访问
            - Before=2031-04-13T11:11:11.010+08:00[Asia/Shanghai]  #这个时间点之前允许访问
      default-filters: #默认过滤器，全局的
        - AddRequestHeader=yao,jikai111
      globalcors: # 全局的跨域处理
        add-to-simple-url-handler-mapping: true # 解决options请求被拦截问题
        corsConfigurations:
          '[/**]':
            allowedOrigins: # 允许哪些网站的跨域请求
              - "http://localhost:8090"
              - "http://www.leyou.com"
            allowedMethods: # 允许的跨域ajax的请求方式
              - "GET"
              - "POST"
              - "DELETE"
              - "PUT"
              - "OPTIONS"
            allowedHeaders: "*" # 允许在请求中携带的头信息
            allowCredentials: true # 是否允许携带cookie
            maxAge: 360000 # 这次跨域检测的有效期


