server:
  port: 8099
spring:
  rabbitmq:
    host: 192.168.1.3
    username: jikaigg
    password: yaojikai
    port: 5672
    virtual-host: /
    listener:
      simple:
        prefetch: 1
  datasource:
    url: jdbc:mysql://192.168.1.3:3306/crayon?useSSL=false
    username: root
    password: yaojikai
    driver-class-name: com.mysql.jdbc.Driver
logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.jikaigg.hotal.pojo